# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        OMDoc: 3
        flexiformal: 3
        mathematical proof: 2
        formal proof: 2
        informal proof: 3
        literate programming: 3
        Lean: 3
        MMT: 3
        DRT: 3
        DTS: 3
        philosophy: 3
        
        Isabelle: 2
        Coq: 2
        Mizar: 2
        controlled natural language: 2
        CNL: 2
        metaprogramming: 2
        
        dependent type: 1
        discourse: 1
        semantic: 1
        semantics: 1
        grammar: 1
        proof: 1
        type theory: 1
        natural language: 1
        

# 通知の閾値
score_threshold: 2
